# Generated by Django 4.2.9 on 2025-02-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_rename_user_ticket_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeptunData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neptun_code', models.CharField(blank=True, max_length=6, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('mothers_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
