# Generated by Django 5.1.6 on 2025-02-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_birth_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_place',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
