# Generated by Django 4.2.19 on 2025-03-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ticket', models.ManyToManyField(related_name='tags', to='api.ticket')),
            ],
        ),
    ]
