# Generated by Django 4.2.19 on 2025-03-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ticket_archived_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(related_name='tickets', to='api.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
