# Python környezet telepítése
FROM python:3.10-slim

# Környezet alapbeállításai
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Munka könyvtár beállítása
WORKDIR /app

# Szükséges csomagok telepítése
COPY backend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Projekt fájlok másolása
COPY backend /app

# Alkalmazás futtatása Gunicorn segítségével
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi:application"]
