# Dockerfile-backend
FROM python:3.10-slim

# Alapbeállítások
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Munka könyvtár beállítása
WORKDIR /app

# Szükséges csomagok telepítése
COPY backend/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Projekt fájlok másolása
COPY backend /app

# Nyisd meg a megfelelő portot
EXPOSE 8000

# Alkalmazás futtatása Gunicorn segítségével
CMD ["gunicorn", "--workers", "3", "--bind", "0.0.0.0:8000", "backend.wsgi:application"]
