# Alap image: Node.js 22.11.0
FROM node:22.11.0 AS build

# Munka könyvtár beállítása
WORKDIR /app

# NPM csomagok telepítése
# Másold a react mappában lévő package.json és package-lock.json fájlokat
COPY react/package.json react/package-lock.json ./ 

# NPM csomagok telepítése
RUN npm install

# A React alkalmazás forráskódjának másolása
COPY react/ /app/

# React alkalmazás építése
RUN npm run build

# Alap image: Nginx
FROM nginx:alpine

ARG CACHE_BUST=1
COPY --from=build /app/dist /usr/share/nginx/html

# Portok megnyitása
EXPOSE 80

# Nginx indítása
CMD ["nginx", "-g", "daemon off;"]